backend: "pandas"
file_name: "fmcsa_complaints"
local_file_extension: "csv"
local_path: "scripts/data_examples"

bucket_raw_ini_dir: "bronze/to_process"
bucket_raw_end_dir: "bronze/processed"
bucket_silver_dir: "silver/fmcsa_complaints"
bucket_file_extension: "parquet"

postgres_table: "trusted_fmcsa_complaints"
postgres_action: "replace"
